### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by ruudk** [txase/maximize#4]
`Protocol "https:" not supported. Expected "http:"`

**Comment by infiniteloopltd** [comment]
There still seems to be no support for https?

**Comment by alexey-sh** [comment]
```
(node:6846) DeprecationWarning: ArgumentParser(): following options are renamed: 'addHelp' -> 'add_help'
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:6846) DeprecationWarning: _ActionsContainer.addArgument() is renamed to _ActionsContainer.add_argument()
(node:6846) DeprecationWarning: use add_argument('url', {...}) instead of add_argument([ 'url' ], { ... })
(node:6846) DeprecationWarning: add_argument(): following options are renamed: 'defaultValue' -> 'default'
(node:6846) DeprecationWarning: ArgumentParser.parseArgs() is renamed to ArgumentParser.parse_args()
node:_http_client:177
    throw new ERR_INVALID_PROTOCOL(protocol, expectedProtocol);
    ^

TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:387:5)
    at new ClientRequest (node:_http_client:177:11)
    at request (node:http:96:10)
    at Object.get (node:http:107:15)
    at Function.fetch (/Users/alexeysh/.nvm/versions/node/v18.7.0/lib/node_modules/maximize/maximize.js:35:12)
    at Function.<anonymous> (/Users/alexeysh/.nvm/versions/node/v18.7.0/lib/node_modules/maximize/maximize.js:45:11)
    at Function.<anonymous> (/Users/alexeysh/.nvm/versions/node/v18.7.0/lib/node_modules/maximize/node_modules/seq/index.js:101:24)
    at action (/Users/alexeysh/.nvm/versions/node/v18.7.0/lib/node_modules/maximize/node_modules/seq/index.js:76:11)
    at Object.seq (/Users/alexeysh/.nvm/versions/node/v18.7.0/lib/node_modules/maximize/node_modules/seq/index.js:93:13)
    at saw.next (/Users/alexeysh/.nvm/versions/node/v18.7.0/lib/node_modules/maximize/node_modules/chainsaw/index.js:52:18) {
  code: 'ERR_INVALID_PROTOCOL'
}

Node.js v18.7.0
```
